client1:
  path: "/mnt/data/in/*.csv"
  format: "csv"
  options:
    header: "true"
    inferSchema: "false"
    delimiter: ","
  schema:
    - name: "trip_duration"
      type: "IntegerType"
    - name: "start_time"
      type: "TimestampType"
    - name: "stop_time"
      type: "TimestampType"
    - name: "start_station_id"
      type: "IntegerType"
    - name: "start_station_name"
      type: "StringType"
    - name: "start_station_latitude"
      type: "DoubleType"
    - name: "start_station_longitude"
      type: "DoubleType"
    - name: "end_station_id"
      type: "IntegerType"
    - name: "end_station_name"
      type: "StringType"
    - name: "end_station_latitude"
      type: "DoubleType"
    - name: "end_station_longitude"
      type: "DoubleType"
    - name: "bike_id"
      type: "IntegerType"
    - name: "user_type"
      type: "StringType"
    - name: "birth_year"
      type: "IntegerType"
    - name: "gender"
      type: "IntegerType"
  transformations:
    - type: "filter"
      expression: "start_station_id = 228"
    - type: "withColumn"
      column: "age"
      expression: "year(current_date()) - birth_year"
  output_format: "parquet"
  output_path: "/mnt/data/out/output/client_1_data"